@hostname = http://127.0.0.1
@port = 2015
@urlPrefix = {{hostname}}:{{port}}

POST {{urlPrefix}}/greetings HTTP/1.1
content-type: application/json

{
    "name": "World"
}

### 

PUT {{urlPrefix}}/greetings/1 HTTP/1.1
content-type: application/json

{
    "name": "World"
}

###

DELETE {{urlPrefix}}/greetings/1 HTTP/1.1

